spring:
  application:
    name: tukuntech-api-gateway

  cloud:
    compatibility-verifier:
      enabled: false

    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          "[/**]":
            allowedOrigins:
              - http://localhost:4200
              - https://tukuntech-front.netlify.app
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            exposedHeaders: "*"
            allowCredentials: true

      default-filters:
        - RemoveRequestHeader=Cookie
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

      routes:
        # ========= RUTAS DE OPENAPI (DOCS) =========
        - id: auth-openapi
          uri: https://tukuntech-ms-iam.onrender.com
          predicates:
            - Path=/api/v1/auth/v3/api-docs/**
          filters:
            - RewritePath=/api/v1/auth/v3/api-docs(?<segment>/?.*), /api/v1/v3/api-docs${segment}

        - id: profiles-openapi
          uri: https://tukuntech-ms-profiles.onrender.com
          predicates:
            - Path=/api/v1/profiles/v3/api-docs/**
          filters:
            - RewritePath=/api/v1/profiles/v3/api-docs(?<segment>/?.*), /api/v1/v3/api-docs${segment}

        - id: support-openapi
          uri: https://tukuntech-ms-support.onrender.com
          predicates:
            - Path=/api/v1/support/v3/api-docs/**
          filters:
            - RewritePath=/api/v1/support/v3/api-docs(?<segment>/?.*), /api/v1/v3/api-docs${segment}

        - id: reports-openapi
          uri: https://tukuntech-ms-reports.onrender.com
          predicates:
            - Path=/api/v1/reports/v3/api-docs/**
          filters:
            - RewritePath=/api/v1/reports/v3/api-docs(?<segment>/?.*), /api/v1/v3/api-docs${segment}

        - id: monitoring-openapi
          uri: https://tukuntech-ms-monitoring.onrender.com
          predicates:
            - Path=/api/v1/monitoring/v3/api-docs/**
          filters:
            - RewritePath=/api/v1/monitoring/v3/api-docs(?<segment>/?.*), /api/v1/v3/api-docs${segment}

        - id: care-openapi
          uri: https://tukuntech-ms-care.onrender.com
          predicates:
            - Path=/api/v1/care/v3/api-docs/**
          filters:
            - RewritePath=/api/v1/care/v3/api-docs(?<segment>/?.*), /api/v1/v3/api-docs${segment}

        # ========= RUTAS DE NEGOCIO =========
        - id: auth
          uri: https://tukuntech-ms-iam.onrender.com
          predicates:
            - Path=/api/v1/auth/**

        - id: profiles
          uri: https://tukuntech-ms-profiles.onrender.com
          predicates:
            - Path=/api/v1/profiles/**
          filters:
            - name: CircuitBreaker
              args:
                name: profilesCircuitBreaker
                fallbackUri: forward:/fallback/profiles

        - id: support
          uri: https://tukuntech-ms-support.onrender.com
          predicates:
            - Path=/api/v1/support/**
          filters:
            - name: CircuitBreaker
              args:
                name: supportCircuitBreaker
                fallbackUri: forward:/fallback/support

        - id: reports
          uri: https://tukuntech-ms-reports.onrender.com
          predicates:
            - Path=/api/v1/reports/**
          filters:
            - name: CircuitBreaker
              args:
                name: reportsCircuitBreaker
                fallbackUri: forward:/fallback/reports

        - id: monitoring
          uri: https://tukuntech-ms-monitoring.onrender.com
          predicates:
            - Path=/api/v1/monitoring/**
          filters:
            - name: CircuitBreaker
              args:
                name: monitoringCircuitBreaker
                fallbackUri: forward:/fallback/monitoring

        - id: care
          uri: https://tukuntech-ms-care.onrender.com
          predicates:
            - Path=/api/v1/care/**
          filters:
            - name: CircuitBreaker
              args:
                name: careCircuitBreaker
                fallbackUri: forward:/fallback/care

server:
  port: 8081

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /api/v1/swagger-ui.html
    urls:
      - name: auth-service
        url: /api/v1/auth/v3/api-docs
      - name: profiles-service
        url: /api/v1/profiles/v3/api-docs
      - name: support-service
        url: /api/v1/support/v3/api-docs
      - name: reports-service
        url: /api/v1/reports/v3/api-docs
      - name: monitoring-service
        url: /api/v1/monitoring/v3/api-docs
      - name: care-service
        url: /api/v1/care/v3/api-docs

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

# ===================== RESILIENCE4J =====================
resilience4j:
  circuitbreaker:
    instances:
      authCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      profilesCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      supportCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      reportsCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      monitoringCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      careCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
